package Strings_durga_sir;

public class demo_hashcode {
	
	public  static void main(String[] args) {
		/*hash code doesn't define address
		hashcode is generated by jvm*/
		
		String s="basava";
		String s1=new String("basava");
		System.out.println(s.equals(s1));
		System.out.println(s==s1);

		System.out.println("null");
		System.out.println(s);
	
	
		  
		
		
	}
	
	

}
